[test]
root = "packages"
preload = ["./packages/bun-plugin/src/index.ts", "./bun.setup.ts", "bun-test-env-dom"]
coverage = true
coverageReporter  = ["text", "lcov"] 
coverageThreshold = { line = 1.0, function = 1.0, statement = 1.0 }
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["**/pkg/**", "**/dist/**", "**/bun-plugin/src/plugin.ts"]
